#!/bin/sh
set -e
case "$1" in
    remove|purge)
        if command -v udevadm >/dev/null 2>&1; then
            udevadm control --reload-rules 2>/dev/null || true
        fi
        command -v update-desktop-database >/dev/null 2>&1 && \
            update-desktop-database -q /usr/share/applications 2>/dev/null || true
        command -v gtk-update-icon-cache >/dev/null 2>&1 && \
            gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor 2>/dev/null || true
        ;;
esac
exit 0
